name: Build

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-server:
    runs-on: ubuntu-latest
    name: Build Server
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Maven Build Server
        run: mvn package
        working-directory: Server

  build-parser:
    runs-on: ubuntu-latest
    name: Build Parser
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Maven Build Parser
        run: mvn package
        working-directory: Parser

  checkstyle-server:
    name: Checkstyle Server
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Maven Checkstyle Server
        run: mvn checkstyle:check modernizer:modernizer spotbugs:check pmd:check pmd:cpd-check
        working-directory: Server

  checkstyle-parcer:
    name: Checkstyle Parcer
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Maven Checkstyle Parcer
        run: mvn checkstyle:check modernizer:modernizer spotbugs:check pmd:check pmd:cpd-check
        working-directory: Parser
